import React, { useState, useContext, useRef, useEffect } from 'react';
import { Send, Info, ArrowUp, Loader2, User, Bot } from 'lucide-react';
import { ProjectContext } from '../../App';
import { performAIAction } from '../../services/geminiService';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

export function ChatTab() {
  const context = useContext(ProjectContext);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || !context) return;
    
    const userMsg: Message = { role: 'user', content: input };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    try {
      const res = await performAIAction(
        { 
          type: 'chat',
          projectName: context.projectName,
          projectType: context.projectType,
          additionalInfo: context.additionalInfo,
          specialQuestion: input,
          history: messages.map(m => ({ role: m.role, content: m.content }))
        },
        context.normativeFiles,
        context.projectFiles
      );
      
      const aiMsg: Message = { role: 'assistant', content: res || '' };
      setMessages(prev => [...prev, aiMsg]);
    } catch (error) {
      console.error(error);
      setMessages(prev => [...prev, { role: 'assistant', content: 'An error occurred while processing the question.' }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-50/30">
      <div ref={scrollRef} className="flex-1 overflow-y-auto p-8 space-y-6">
        <div className="bg-white border border-slate-100 rounded-2xl p-6 flex items-start gap-4 max-w-4xl mx-auto shadow-sm">
          <Info className="w-5 h-5 text-slate-400 shrink-0 mt-0.5" />
          <p className="text-[11px] text-slate-400 leading-relaxed italic">
            Disclaimer: In all domains, this data is generated by AI and has approximately 90% accuracy. The provided answers are advisory. Final responsibility lies with the designer.
          </p>
        </div>

        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center text-center py-12 space-y-4">
            <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mb-2">
              <Bot className="w-8 h-8 text-blue-500" />
            </div>
            <h2 className="text-2xl font-bold text-slate-800">7. AI Assistant (Chat)</h2>
            <p className="text-sm text-slate-500 leading-relaxed max-w-2xl">
              This is your personal AI assistant. It is familiar with the context of your uploaded files and the analyses received.
            </p>
          </div>
        )}

        <div className="max-w-4xl mx-auto space-y-6">
          {messages.map((msg, i) => (
            <div key={i} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 shadow-sm ${msg.role === 'user' ? 'bg-blue-600' : 'bg-white border border-slate-200'}`}>
                {msg.role === 'user' ? <User className="w-5 h-5 text-white" /> : <Bot className="w-5 h-5 text-blue-500" />}
              </div>
              <div className={`p-5 rounded-2xl max-w-[80%] shadow-sm ${msg.role === 'user' ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-700'}`}>
                <div className="prose prose-sm max-w-none prose-slate">
                  <ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{msg.content}</ReactMarkdown>
                </div>
              </div>
            </div>
          ))}
          {loading && (
            <div className="flex gap-4">
              <div className="w-10 h-10 rounded-xl bg-white border border-slate-200 flex items-center justify-center shrink-0 shadow-sm">
                <Loader2 className="w-5 h-5 text-blue-500 animate-spin" />
              </div>
              <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-sm">
                <div className="flex gap-1">
                  <div className="w-1.5 h-1.5 bg-slate-300 rounded-full animate-bounce" />
                  <div className="w-1.5 h-1.5 bg-slate-300 rounded-full animate-bounce [animation-delay:0.2s]" />
                  <div className="w-1.5 h-1.5 bg-slate-300 rounded-full animate-bounce [animation-delay:0.4s]" />
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="p-8 border-t border-slate-100 bg-white">
        <div className="max-w-4xl mx-auto relative">
          <input 
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Write your question here..."
            className="w-full px-6 py-5 bg-slate-50 border border-slate-200 rounded-2xl text-sm text-slate-600 placeholder:text-slate-300 focus:outline-none focus:border-blue-500 transition-all shadow-inner pr-16"
          />
          <button 
            onClick={handleSend}
            disabled={loading || !input.trim()}
            className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 bg-blue-600 text-white rounded-xl flex items-center justify-center hover:bg-blue-700 transition-all shadow-md disabled:opacity-50"
          >
            <ArrowUp className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
}
