import React, { useState, useContext } from 'react';
import { BarChart3, Play, Loader2, FileSpreadsheet, X, Download, Info, CheckCircle2 } from 'lucide-react';
import { ProjectContext } from '../../App';
import { performAIAction } from '../../services/geminiService';
import * as XLSX from 'xlsx';

export function VolumesTab() {
  const context = useContext(ProjectContext);
  if (!context) return null;
  const { 
    volumesResult: result, setVolumesResult: setResult,
    volumesParsedData: parsedData, setVolumesParsedData: setParsedData 
  } = context;
  const [loading, setLoading] = useState(false);
  const [estimateFile, setEstimateFile] = useState<File | null>(null);
  const [actualFile, setActualFile] = useState<File | null>(null);
  const [specialQuestion, setSpecialQuestion] = useState('');
  const [template, setTemplate] = useState('');

  const handleAudit = async () => {
    if (!context || !estimateFile || !actualFile) return;
    setLoading(true);
    setParsedData(null);
    try {
      const res = await performAIAction(
        { 
          type: 'volumes',
          projectName: context.projectName,
          projectType: context.projectType,
          additionalInfo: context.additionalInfo,
          specialQuestion: specialQuestion || template || "Compare the estimated and actual execution volumes. Find the deviations."
        },
        context.normativeFiles,
        context.projectFiles,
        { estimate: estimateFile, actual: actualFile }
      );
      
      setResult(res || '');
      
      try {
        // Try to extract JSON from the response if it's wrapped in markdown
        const jsonMatch = res?.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          const data = JSON.parse(jsonMatch[0]);
          setParsedData(data);
        }
      } catch (e) {
        console.error("Failed to parse AI JSON response", e);
      }
    } catch (error) {
      console.error(error);
      setResult('An error occurred during volumes comparison.');
    } finally {
      setLoading(false);
    }
  };

  const exportToExcel = () => {
    if (!parsedData) return;

    const tableData = [
      ["Work Name", "Unit", "Estimated Qty", "Actual Qty", "Deviation", "Unit Price", "Total Price"],
      ...parsedData.table.map((row: any) => [
        row.name,
        row.unit,
        row.estimateQty,
        row.actualQty,
        row.deviation,
        row.unitPrice,
        row.totalPrice
      ])
    ];

    const ws = XLSX.utils.aoa_to_sheet(tableData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Volumes Comparison");
    XLSX.writeFile(wb, `Volumes_Comparison_${context?.projectName || 'Project'}.xlsx`);
  };

  return (
    <div className="flex-1 overflow-y-auto p-8 space-y-8">
      <div className="space-y-4">
        <h2 className="text-2xl font-bold text-slate-800">5. Volumes (Actual vs Estimate)</h2>
        <p className="text-sm text-slate-500 leading-relaxed max-w-3xl">
          This tool compares estimated volumes with actual execution acts. It finds increased or decreased volumes, price deviations, and presents a summary report.
        </p>
      </div>

      {/* Info Banner */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 flex items-start gap-3">
        <Info className="w-5 h-5 text-slate-400 shrink-0 mt-0.5" />
        <p className="text-[11px] text-slate-500 leading-relaxed">
          Disclaimer: In all domains, this data is generated by AI and has approximately 90% accuracy. The provided answers are advisory. Final responsibility lies with the designer.
        </p>
      </div>

      {parsedData && (
        <div className="flex items-center justify-end gap-3">
          <button 
            onClick={exportToExcel}
            className="flex items-center gap-2 px-6 py-2.5 bg-[#00875a] text-white rounded-lg text-xs font-bold hover:bg-[#006644] transition-all shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export to Excel
          </button>
        </div>
      )}

      {!parsedData && (
        <>
          {/* Guide Section */}
          <div className="bg-blue-50/50 border border-blue-100 rounded-3xl p-8 space-y-6">
            <div className="flex items-center gap-3 text-blue-800 font-bold text-sm">
              <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                <FileSpreadsheet className="w-4 h-4 text-blue-600" />
              </div>
              WHAT THE FILES SHOULD LOOK LIKE (VISUAL)
            </div>

            <div className="space-y-2">
              <p className="text-[10px] font-bold text-blue-400 uppercase tracking-widest">Example Estimate</p>
              
              {/* Mock Excel UI */}
              <div className="bg-white rounded-xl border border-slate-200 shadow-xl overflow-hidden max-w-4xl">
                {/* Excel Toolbar */}
                <div className="bg-[#f3f2f1] border-b border-slate-200 p-2 flex items-center gap-4">
                  <div className="flex items-center gap-1 border-r border-slate-300 pr-4">
                    <div className="w-3 h-3 rounded-full bg-slate-300" />
                    <div className="w-3 h-3 rounded-full bg-slate-300" />
                    <div className="w-3 h-3 rounded-full bg-slate-300" />
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="h-6 w-20 bg-white border border-slate-300 rounded text-[10px] flex items-center px-2 text-slate-400 font-mono">A1</div>
                    <div className="h-6 w-40 bg-white border border-slate-300 rounded text-[10px] flex items-center px-2 text-slate-400 font-mono italic">fx</div>
                  </div>
                </div>

                {/* Excel Grid */}
                <div className="overflow-x-auto">
                  <table className="w-full border-collapse text-[11px]">
                    <thead>
                      <tr className="bg-[#f8f9fa]">
                        <th className="w-10 border border-slate-200 bg-[#f8f9fa] text-slate-400 font-normal"></th>
                        <th className="border border-slate-200 p-1.5 text-slate-500 font-medium w-1/3">A</th>
                        <th className="border border-slate-200 p-1.5 text-slate-500 font-medium">B</th>
                        <th className="border border-slate-200 p-1.5 text-slate-500 font-medium">C</th>
                        <th className="border border-slate-200 p-1.5 text-slate-500 font-medium">D</th>
                        <th className="border border-slate-200 p-1.5 text-slate-500 font-medium">E</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td className="bg-[#f8f9fa] border border-slate-200 text-center text-slate-400">1</td>
                        <td colSpan={5} className="border border-slate-200 p-3 font-bold text-lg text-slate-800">Construction Estimate</td>
                      </tr>
                      <tr>
                        <td className="bg-[#f8f9fa] border border-slate-200 text-center text-slate-400">2</td>
                        <td className="border border-slate-200 p-2 bg-blue-100/50 font-bold text-slate-700">Work Name</td>
                        <td className="border border-slate-200 p-2 bg-blue-100/50 font-bold text-slate-700 text-center">Unit</td>
                        <td className="border border-slate-200 p-2 bg-blue-100/50 font-bold text-slate-700 text-center">Qty</td>
                        <td className="border border-slate-200 p-2 bg-blue-100/50 font-bold text-slate-700 text-center">Unit Price</td>
                        <td className="border border-slate-200 p-2 bg-blue-100/50 font-bold text-slate-700 text-center">Total</td>
                      </tr>
                      {[
                        { name: 'Foundation works', unit: 'm3', qty: '120', price: '$2,500', total: '$300,000' },
                        { name: 'Wall masonry', unit: 'm2', qty: '450', price: '$8,000', total: '$3,600,000' },
                        { name: 'Roof construction', unit: 'm2', qty: '180', price: '$15,000', total: '$2,700,000' },
                        { name: 'Internal plaster', unit: 'm2', qty: '600', price: '$3,500', total: '$2,100,000' },
                      ].map((row, i) => (
                        <tr key={i}>
                          <td className="bg-[#f8f9fa] border border-slate-200 text-center text-slate-400">{i + 3}</td>
                          <td className="border border-slate-200 p-2 text-slate-600">{row.name}</td>
                          <td className="border border-slate-200 p-2 text-center text-slate-600">{row.unit}</td>
                          <td className="border border-slate-200 p-2 text-center text-slate-600 font-mono">{row.qty}</td>
                          <td className="border border-slate-200 p-2 text-center text-slate-600 font-mono">{row.price}</td>
                          <td className="border border-slate-200 p-2 text-center text-slate-600 font-mono font-bold">{row.total}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Estimate Upload */}
            <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 space-y-4">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                <CheckCircle2 className={`w-4 h-4 ${estimateFile ? 'text-green-500' : 'text-slate-300'}`} />
                Estimate
              </h3>
              {!estimateFile ? (
                <label className="flex flex-col items-center justify-center py-10 border-2 border-dashed border-slate-200 rounded-xl bg-white cursor-pointer hover:border-blue-400 transition-all group">
                  <FileSpreadsheet className="w-8 h-8 text-slate-300 mb-2 group-hover:text-blue-400 transition-colors" />
                  <span className="text-[10px] font-bold text-slate-400">ATTACH ESTIMATE</span>
                  <input type="file" className="hidden" onChange={e => e.target.files && setEstimateFile(e.target.files[0])} />
                </label>
              ) : (
                <div className="flex items-center justify-between p-3 bg-white border border-slate-200 rounded-xl shadow-sm">
                  <div className="flex items-center gap-3 overflow-hidden">
                    <div className="w-8 h-8 bg-green-50 rounded-lg flex items-center justify-center shrink-0">
                      <FileSpreadsheet className="w-4 h-4 text-green-500" />
                    </div>
                    <span className="text-xs font-bold text-slate-600 truncate">{estimateFile.name}</span>
                  </div>
                  <button onClick={() => setEstimateFile(null)} className="text-slate-400 hover:text-red-500 p-1">
                    <X className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>

            {/* Actual Upload */}
            <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 space-y-4">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                <CheckCircle2 className={`w-4 h-4 ${actualFile ? 'text-blue-500' : 'text-slate-300'}`} />
                Actual
              </h3>
              {!actualFile ? (
                <label className="flex flex-col items-center justify-center py-10 border-2 border-dashed border-slate-200 rounded-xl bg-white cursor-pointer hover:border-blue-400 transition-all group">
                  <FileSpreadsheet className="w-8 h-8 text-slate-300 mb-2 group-hover:text-blue-400 transition-colors" />
                  <span className="text-[10px] font-bold text-slate-400">ATTACH ACTUAL</span>
                  <input type="file" className="hidden" onChange={e => e.target.files && setActualFile(e.target.files[0])} />
                </label>
              ) : (
                <div className="flex items-center justify-between p-3 bg-white border border-slate-200 rounded-xl shadow-sm">
                  <div className="flex items-center gap-3 overflow-hidden">
                    <div className="w-8 h-8 bg-blue-50 rounded-lg flex items-center justify-center shrink-0">
                      <FileSpreadsheet className="w-4 h-4 text-blue-500" />
                    </div>
                    <span className="text-xs font-bold text-slate-600 truncate">{actualFile.name}</span>
                  </div>
                  <button onClick={() => setActualFile(null)} className="text-slate-400 hover:text-red-500 p-1">
                    <X className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>
          </div>
          
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">SPECIAL QUESTION FOR VOLUMES (OPTIONAL)</h3>
            </div>
            <p className="text-[10px] text-slate-400 italic">If you have a specific question, state it here, and the AI will focus on it first:</p>
            <textarea 
              value={specialQuestion}
              onChange={(e) => setSpecialQuestion(e.target.value)}
              placeholder="Example: Do the concrete volumes match the design indicators..."
              rows={4}
              className="w-full px-6 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-xs text-slate-600 placeholder:text-slate-300 focus:outline-none focus:border-blue-500 transition-all resize-none italic"
            />
            
            <div className="pt-2 border-t border-slate-100">
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-2">OR CHOOSE FROM TEMPLATE</label>
              <select 
                value={template}
                onChange={(e) => setTemplate(e.target.value)}
                className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl text-xs focus:outline-none focus:border-blue-500 transition-all shadow-sm"
              >
                <option value="">-- Select a saved query --</option>
                {context.templates.map(t => (
                  <option key={t.id} value={t.title}>{t.title}</option>
                ))}
              </select>
            </div>
          </div>

          <button 
            disabled={!estimateFile || !actualFile || loading}
            onClick={handleAudit}
            className="w-full py-4 bg-blue-600 text-white rounded-2xl font-bold text-sm flex items-center justify-center gap-3 hover:bg-blue-700 transition-all shadow-lg shadow-blue-600/20 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-current" />}
            COMPARE VOLUMES
          </button>
        </>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center py-20">
          <Loader2 className="w-10 h-10 text-blue-500 animate-spin mb-4" />
          <p className="text-slate-500 text-sm font-medium animate-pulse">Comparing volumes...</p>
        </div>
      )}

      {parsedData && (
        <div id="volumes-results" className="flex flex-col gap-8 animate-in fade-in slide-in-from-bottom-4 duration-500 p-4 bg-white">
          {/* Table Area */}
          <div className="w-full space-y-6">
            <div className="bg-white border border-[#e2e8f0] rounded-3xl overflow-hidden shadow-sm">
              <div className="p-6 border-b border-[#f1f5f9] flex items-center justify-between">
                <h3 className="text-lg font-bold text-[#1e293b]">Comparison Table</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse min-w-[800px]">
                  <thead>
                    <tr className="bg-[#f8fafc]">
                      <th className="px-6 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9]">WORK NAME</th>
                      <th className="px-4 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">UNIT</th>
                      <th className="px-4 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">ESTIMATE</th>
                      <th className="px-4 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">ACTUAL</th>
                      <th className="px-4 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">DEVIATION</th>
                      <th className="px-4 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">PRICE</th>
                      <th className="px-6 py-4 text-[10px] font-bold text-[#94a3b8] uppercase tracking-wider border-b border-[#f1f5f9] text-center">STATUS</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#f8fafc]">
                    {parsedData.table.map((row: any, i: number) => (
                      <tr key={i} className="hover:bg-[#f8fafc] transition-colors">
                        <td className="px-6 py-4 text-xs font-bold text-[#334155]">{row.name}</td>
                        <td className="px-4 py-4 text-xs text-[#64748b] text-center">{row.unit}</td>
                        <td className="px-4 py-4 text-xs font-mono text-[#475569] text-center">{row.estimateQty.toLocaleString()}</td>
                        <td className="px-4 py-4 text-xs font-mono text-[#475569] text-center">{row.actualQty.toLocaleString()}</td>
                        <td className={`px-4 py-4 text-xs font-mono text-center font-bold ${row.deviation > 0 ? 'text-[#ef4444]' : row.deviation < 0 ? 'text-[#059669]' : 'text-[#94a3b8]'}`}>
                          {row.deviation > 0 ? `+${row.deviation.toLocaleString()}` : row.deviation.toLocaleString()}
                        </td>
                        <td className="px-4 py-4 text-center">
                          <div className="flex flex-col items-center">
                            <span className="text-[9px] text-[#94a3b8] font-mono">${row.unitPrice.toLocaleString()}</span>
                            <span className="text-xs font-bold text-[#334155] font-mono">${row.totalPrice.toLocaleString()}</span>
                          </div>
                        </td>
                        <td className="px-6 py-4 text-center">
                          <div className="flex justify-center">
                            {row.status === 'success' && <div className="w-6 h-6 bg-[#d1fae5] rounded-full flex items-center justify-center"><CheckCircle2 className="w-3.5 h-3.5 text-[#059669]" /></div>}
                            {row.status === 'warning' && <div className="w-6 h-6 bg-[#fee2e2] rounded-full flex items-center justify-center"><Info className="w-3.5 h-3.5 text-[#dc2626]" /></div>}
                            {row.status === 'info' && <div className="w-6 h-6 bg-[#dbeafe] rounded-full flex items-center justify-center"><Info className="w-3.5 h-3.5 text-[#2563eb]" /></div>}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Summary Area */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 bg-white border border-[#e2e8f0] rounded-3xl p-8 shadow-sm">
              <div className="flex flex-col lg:flex-row justify-between gap-12">
                <div className="space-y-8 flex-1">
                  <h3 className="text-lg font-bold text-[#1e293b]">AI Summary</h3>
                  <div className="space-y-6">
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-[#94a3b8] uppercase tracking-widest">TOTAL ESTIMATE</p>
                      <p className="text-2xl font-bold text-[#1e293b] font-mono">${parsedData.summary.totalEstimate.toLocaleString()}</p>
                    </div>
                    
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-[#94a3b8] uppercase tracking-widest">TOTAL ACTUAL COST</p>
                      <p className="text-2xl font-bold text-[#ef4444] font-mono">${parsedData.summary.totalActual.toLocaleString()}</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <p className="text-[10px] font-bold text-[#94a3b8] uppercase tracking-widest">COMPLETION PERCENTAGE</p>
                      <p className="text-xs font-bold text-[#334155]">{parsedData.summary.completionPercentage}%</p>
                    </div>
                    <div className="h-2 bg-[#f1f5f9] rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-[#2563eb] rounded-full transition-all duration-1000" 
                        style={{ width: `${parsedData.summary.completionPercentage}%` }}
                      />
                    </div>
                  </div>
                </div>

                <div className="lg:w-px lg:bg-[#f1f5f9]" />

                <div className="space-y-4 flex-1">
                  <h4 className="text-[10px] font-bold text-[#b45309] uppercase tracking-widest">MAIN DEVIATIONS</h4>
                  <ul className="space-y-3">
                    {parsedData.summary.deviations.map((dev: string, i: number) => (
                      <li key={i} className="flex items-start gap-3">
                        <div className="w-1.5 h-1.5 bg-[#b45309] rounded-full shrink-0 mt-1.5" />
                        <p className="text-xs text-[#475569] leading-relaxed">{dev}</p>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            <div className="flex flex-col justify-center items-center bg-[#f8fafc] border border-[#e2e8f0] rounded-3xl p-8">
              <button 
                onClick={() => { setParsedData(null); setResult(''); }}
                className="w-full py-4 bg-white border border-[#e2e8f0] rounded-2xl text-xs font-bold text-[#64748b] hover:text-[#dc2626] hover:border-[#fee2e2] uppercase tracking-widest transition-all shadow-sm"
              >
                CLEAR RESULTS
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
